# Generated by Django 2.2.2 on 2019-06-22 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('response1', models.TextField()),
                ('response2', models.TextField()),
                ('response3', models.TextField()),
                ('correct_response', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv1.UserDocument')),
            ],
        ),
    ]
