# Generated by Django 2.2.2 on 2019-06-23 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='apiv1.UserDocument'),
        ),
    ]
