# Generated by Django 2.2.2 on 2019-06-23 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0003_auto_20190623_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='apiv1.UserDocument'),
        ),
    ]
