# Generated by Django 2.2.2 on 2019-07-03 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0004_auto_20190623_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='correct_response',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='response1',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='response2',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='response3',
        ),
    ]
